### ISSUE TITLE
Wrong namespace in CMake config

### ISSUE THREAD

**Issue by nickdademo** [DNKpp/mimicpp#60]
https://github.com/DNKpp/mimicpp/blob/290900cde94653501e104eaa9aaea4713cec316b/cmake/InstallRules.cmake#L41

Should this be `mimicpp::mimicpp`? (to match the documentation)

**Comment by DNKpp** [comment]
Nice catch! Thank you.

May I ask how you actually integrate ``mimic++`` into your project? Do you actually use the install-package?

**Comment by nickdademo** [comment]
> Nice catch! Thank you.
> 
> May I ask how you actually integrate `mimic++` into your project? Do you actually use the install-package?

No problem! Actually, I just created a `vcpkg` port for `mimicpp` ;) https://github.com/microsoft/vcpkg/pull/41684

**Comment by DNKpp** [comment]
Oh, that's cool. Thank you very much :)
Issue should be fixed on dev and will be part of the next release.
